-- MySQL Script generated by MySQL Workbench
-- sam. 24 sept. 2016 23:09:28 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

CREATE TABLE IF NOT EXISTS `session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` VARCHAR(45) NOT NULL,
  `infos` TEXT NOT NULL,
  `event_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_session_event_idx` (`event_id` ASC),
  CONSTRAINT `fk_session_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `result` ;

CREATE TABLE IF NOT EXISTS `result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `driver_name` VARCHAR(200) NULL,
  `fastest_lap` VARCHAR(10) NULL,
  `average_lap` VARCHAR(10) NULL,
  `lap_count` INT(11) NULL,
  `session_id` INT NOT NULL,
  `car` VARCHAR(45) NULL,
  `incidents` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_result_session1_idx` (`session_id` ASC),
  CONSTRAINT `fk_result_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
